services:
  api:
    image: eth-wallet-api
    container_name: eth-wallet-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:3001
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  frontend:
    image: eth-wallet-frontend
    container_name: eth-wallet-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - ${FRONTEND_PORT}:3000
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: eth-wallet-postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ${VOLUME_PATH}/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
